### 怎样理解卷积层的权重？

In [13]:
# 卷积层的权重就是卷积核（也称为滤波器）。卷积核是可学习的，每个卷积核就是一个小的权重tensor，这个tensor与输入数据的局部区域进行点乘操作，然后滑过整个输入数据，生成输出特征图。
# 卷积核是一个的形状为(out_channels, in_channels, kernel_height, kernel_width)的四维tensor，所以我们不能说卷积核是一个矩阵。
# 尽管从技术角度讲，卷积核是由一个四维张量表示的，但当我们单独考虑每个卷积核时，可以说每个卷积核本质上是一个三维张量(in_channels, kernel_height, kernel_width)。
# 这是因为每个输出通道对应于一组跨所有输入通道的卷积核。例如，在处理RGB图像时，如果定义了一个 Conv2d 层如下：
# rgb_conv_layer = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3)
# 那么，这个rgb_conv_layer将会有16个卷积核，每个卷积核都是一个形状为(3, 3, 3)的三维张量，用于与输入图像的每个对应部分进行卷积操作。

import torch.nn as nn

conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1, bias=False)

# 对于卷积层conv_layer，其权重是conv_layer.weight，其形状为(1, 1, 3, 3)
print(conv_layer.weight.shape)
print(conv_layer.weight)

print("-----------------------------------------------------------------")

rgb_conv_layer = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1, bias=False)

# 对于卷积层rgb_conv_layer，其权重是rgb_conv_layer.weight，其形状为(16, 3, 3, 3)
print(rgb_conv_layer.weight.shape)
print(rgb_conv_layer.weight)

torch.Size([1, 1, 3, 3])
Parameter containing:
tensor([[[[-0.2615, -0.0957, -0.1822],
          [-0.1986, -0.2467,  0.1722],
          [ 0.1216,  0.1003, -0.1553]]]], requires_grad=True)
-----------------------------------------------------------------
torch.Size([16, 3, 3, 3])
Parameter containing:
tensor([[[[-5.7309e-02, -4.0838e-02,  2.4207e-02],
          [-3.6228e-03,  1.3015e-01,  1.3956e-01],
          [ 1.4355e-01,  1.8553e-02,  1.4893e-01]],

         [[ 1.3485e-01,  8.5132e-02, -6.8204e-02],
          [-1.0675e-01,  1.6574e-01, -1.1563e-01],
          [-1.1286e-01, -4.9994e-02, -1.1562e-01]],

         [[-1.6132e-01, -5.7778e-03,  1.7284e-01],
          [-1.0774e-01,  1.5583e-01, -1.7318e-01],
          [ 5.3943e-02, -2.4681e-02,  6.8387e-02]]],


        [[[ 5.6381e-02, -2.8923e-02,  8.7376e-02],
          [-1.3475e-02, -9.4163e-02, -1.8665e-01],
          [ 7.1013e-02, -9.6272e-02, -1.7661e-01]],

         [[ 1.4766e-01,  1.9146e-01, -1.6736e-01],
          [ 1.4840e-01, -1

In [14]:
# 输入是一个 5x5 的简单灰度图像
input_data = torch.tensor([[1., 2., 0., 0., 1.],
                           [0., 1., 2., 1., 0.],
                           [1., 1., 1., 0., 1.],
                           [0., 2., 2., 1., 0.],
                           [1., 1., 0., 1., 1.]])

# 添加批次维度和通道维度
input_data = input_data.unsqueeze(0).unsqueeze(0)  # 形状变为 (1, 1, 5, 5)

In [16]:
output = conv_layer(input_data)
print(output.shape)
print(output)

torch.Size([1, 1, 5, 5])
tensor([[[[-0.0576, -0.9025, -0.2305,  0.5157, -0.1251],
          [-0.3430, -0.2886, -0.8210, -0.8600, -0.1940],
          [-0.5674, -0.8434, -0.7920, -0.3016, -0.3866],
          [ 0.0115, -0.4665, -1.1094, -1.1428, -0.0724],
          [-0.4390, -1.0012, -0.9230, -0.6932, -0.7069]]]],
       grad_fn=<ConvolutionBackward0>)
